baseurl: 
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  media: 'public/images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "event_date"
        field:
          element: "text"
          label: "Event Date"
          placeholder: "June 18, 2014"
          type: "text"
      - name: "post_smallimg"
        field:
          element: "text"
          label: "Small Post Image"
          help: "Once you have uploaded the image (400x300), write the name of the image. Convention : imagename.jpg"
          placeholder: "imagename.jpg"
          type: "text"
    _posts/heritage:
      - name: "heritage_img"
      field:
          element: "text"
          label: "Small Post Image"
          help: "Once you have uploaded the image (400x300), write the name of the image. Convention : imagename.jpg"
          placeholder: "imagename.jpg"
          type: "text"

    _posts/about:
      - name: "member_img"
      field:
          element: "text"
          label: "Small Post Image"
          help: "Once you have uploaded the image (400x300), write the name of the image. Convention : imagename.jpg"
          placeholder: "imagename.jpg"
          type: "text"
